# Generated by Django 4.1.5 on 2023-05-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_expense_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
