# Generated by Django 4.1.5 on 2023-05-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_payments_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Expense',
        ),
    ]
