# Generated by Django 4.1.5 on 2023-05-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_payment_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payed',
            new_name='isPayed',
        ),
    ]
