# Generated by Django 4.1.5 on 2023-05-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_payed_expense_ispayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='houseHold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.household'),
            preserve_default=False,
        ),
    ]
