# Generated by Django 4.1.5 on 2023-05-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_expense_household'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='houseHold',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='houseHold',
            new_name='household',
        ),
    ]
