# Generated by Django 4.1.5 on 2023-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_household_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=16),
        ),
    ]
